english_translation={
"Monthes"            :"Monthes",
"Packing materials"  :"Packing materials",
"Active Orders"      :"Action Orders",
"Final Products"     :"Final Products",
"HOME"               :"HOME",
'Products'           :'Products',
'Measuring Units'    :'Measuring Units',
'Raw Materials'      :'Raw Materials',
"Product Raw Materials":'Product Raw Materials',
'Orders'             :'Orders',
"Products"           :"Products",
"File"               :"File",
"Export"             :"Export",
"Import"             :"Import",
"View"               :"View",
"Themes"             :"Themes",
"Excell"             :"Excell",
"Word"               :"Word",
"INS Production Plan Document" :"INS Production Plan Guide book",
"About"              :"About",
"Backup"             :"Backup",
"Backup settings"    :"Backup settings",
"INS"                :"INS",
"White"              :"White",
"Dark Green"         :"Dark Green",
"Dark Blue"          :"Dark Blue",
"Language"           :"Language",
'Order Name'         :'Order Name',
'Quantity'           :'Quantity',
'From'               :'From',
'To'                 :'To',
'Add Order'          :'Add Order',
'Edit Order'         :'Edit Order',
"Material Name"      :"Material Name",
"Available Quantity" :"Available Quantity",
"Code"               :"Code",
'Add Material'       :'Add Material',
'Edit Material'      :'Edit Material' ,
"Material density"      :'Material density',
"Matiral Types"         :"Matiral Types",
"Product Name"          :"Product Name",
'Add Product'          :'Add Product',
'Edit Product'         :'Edit Product',
"Unit Name"             :"Unit Name",
"Value"                 :"Value",
'Add Unit'              :'Add Unit',
'Edit Unit'             :'Edit Unit',
"Manual backup"         :"Manual backup",
"Auto backup"           :"Auto backup",
"Year"                  :"Year",
"Month"                 :"Month",
"Day"                   :"Day",
"Hour"                  :"Hour",
"Backup every"          :"Backup every",
"Cancel"                :"Cancel",
"Apply"                 :"Apply",
"Create Backup"         :"Create Backup",
"Export Excel"          :"Export Excel",
}

arabic_translation={
"Monthes"              :"الشهور",
"Packing materials"    :"مواد التغليف",
"Active Orders"        :"طلبات قيد التنفيذ",
"Final Products"       :"المنتجات النهائية",
"HOME"                 :"الصفحة الرئيسية",
'Products'             :'صفحة المنتجات',
'Measuring Units'      :'وحدات القياس',
'Raw Materials'        :'المواد الأولية',
'Product Raw Materials':'المواد الأولية للمنتج',
'Orders'               :'الطلبات',
"Products"             :"المنتجات",
"File"                 :"ملف",
"Export"               :"استخراج",
"Import"               :"استيراد",
"View"                 :"عرض",
"Themes"               :"نمط",
"Excell"               :"Excell",
"Word"                 :"Word",
"INS Production Plan Document"   :"INS Production Plan دليل",
"About"                :"حول",
"Backup"               :"نسخ إحتياطي",
"Backup settings"      :"اعدادات النسخ الإحتياطي",
"INS"                  :"INS",
"White"                :"أبيض",
"Dark Green"           :"أخضر داكن",
"Dark Blue"            :"أزرق داكن",
"Language"             :"اللغة",
'Order Name'           :'اسم الطلب',
'Quantity'             :'الكمية',
'From'                 :'من',
'To'                   :'إلى',
'Add Order'            :'إضافة طلب',
'Edit Order'           :'تعديل طلب',
"Material Name"        :"اسم المادة",
"Available Quantity"   :"الكمية المتوفرة",
"Code"                 :"الرمز",
'Add Material'         :'إضافة مادة',
'Edit Material'        :'تعديل مادة',
"Material density"     :'كثافة المادة',
"Matiral Types"        :'نوع المادة',
"Product Name"         :'اسم المنتج',
'Add Product'          :'إضافة منتج',
'Edit Product'         :'تعديل المنتج',
"Unit Name"             :"اسم الواحدة",
"Value"                 :"القيمة",
'Add Unit'              :'إضافة واحدة',
'Edit Unit'             :'تعديل الواحدة',
"Manual backup"         :"نسخ احتياطي يدوي",
"Auto backup"           :"نسخ احتياطي تلقائي",
"Year"                  :"سنة",
"Month"                 :"شهر",
"Day"                   :"يوم",
"Hour"                  :"ساعة",
"Backup every"          :"نسخ احتياطي كل",
"Cancel"                :"إلغاء",
"Apply"                 :"تطبيق",
"Create Backup"         :"انشاء نسخ احتياطي",
"Export Excel"          :'استخراج ملف اكسل',
}

italy_translation={
"Monthes"            :"Monthes",
"Packing materials"  :"Packing materials",
"Active Orders"      :"Action Orders",
"Final Products"     :"Final Products",
"HOME"               :"HOME",
'Products'           :'Products',
'Measuring Units'    :'Measuring Units',
'Raw Materials'      :'Raw Materials',
"Product Raw Materials":'Product Raw Materials',
'Orders'             :'Orders',
"Products"           :"Products",
"File"               :"File",
"Export"             :"Export",
"Import"             :"Import",
"View"               :"View",
"Themes"             :"Themes",
"Excell"             :"Excell",
"Word"               :"Word",
"INS Production Plan Document" :"INS Production Plan Guide book",
"About"              :"About",
"Backup"             :"Backup",
"Backup settings"    :"Backup settings",
"INS"                :"INS",
"White"              :"White",
"Dark Green"         :"Dark Green",
"Dark Blue"          :"Dark Blue",
"Language"           :"Language",
'Order Name'         :'Order Name',
'Quantity'           :'Quantity',
'From'               :'From',
'To'                 :'To',
'Add Order'          :'Add Order',
'Edit Order'         :'Edit Order',
"Material Name"      :"Material Name",
"Available Quantity" :"Available Quantity",
"Code"               :"Code",
'Add Material'       :'Add Material',
'Edit Material'      :'Edit Material' ,
"Material density"      :'Material density',
"Matiral Types"         :"Matiral Types",
"Product Name"          :"Product Name",
'Add Product'          :'Add Product',
'Edit Product'         :'Edit Product',
"Unit Name"             :"Unit Name",
"Value"                 :"Value",
'Add Unit'              :'Add Unit',
'Edit Unit'             :'Edit Unit',
"Manual backup"         :"Manual backup",
"Auto backup"           :"Auto backup",
"Year"                  :"Year",
"Month"                 :"Month",
"Day"                   :"Day",
"Hour"                  :"Hour",
"Backup every"          :"Backup every",
"Cancel"                :"Cancel",
"Apply"                 :"Apply",
"Create Backup"         :"Create Backup",
"Export Excel"          :"Export Excel",
}
french_translation={
"Monthes"            :"Monthes",
"Packing materials"  :"Packing materials",
"Active Orders"      :"Action Orders",
"Final Products"     :"Final Products",
"HOME"               :"HOME",
'Products'           :'Products',
'Measuring Units'    :'Measuring Units',
'Raw Materials'      :'Raw Materials',
"Product Raw Materials":'Product Raw Materials',
'Orders'             :'Orders',
"Products"           :"Products",
"File"               :"File",
"Export"             :"Export",
"Import"             :"Import",
"View"               :"View",
"Themes"             :"Themes",
"Excell"             :"Excell",
"Word"               :"Word",
"INS Production Plan Document" :"INS Production Plan Guide book",
"About"              :"About",
"Backup"             :"Backup",
"Backup settings"    :"Backup settings",
"INS"                :"INS",
"White"              :"White",
"Dark Green"         :"Dark Green",
"Dark Blue"          :"Dark Blue",
"Language"           :"Language",
'Order Name'         :'Order Name',
'Quantity'           :'Quantity',
'From'               :'From',
'To'                 :'To',
'Add Order'          :'Add Order',
'Edit Order'         :'Edit Order',
"Material Name"      :"Material Name",
"Available Quantity" :"Available Quantity",
"Code"               :"Code",
'Add Material'       :'Add Material',
'Edit Material'      :'Edit Material' ,
"Material density"      :'Material density',
"Matiral Types"         :"Matiral Types",
"Product Name"          :"Product Name",
'Add Product'          :'Add Product',
'Edit Product'         :'Edit Product',
"Unit Name"             :"Unit Name",
"Value"                 :"Value",
'Add Unit'              :'Add Unit',
'Edit Unit'             :'Edit Unit',
"Manual backup"         :"Manual backup",
"Auto backup"           :"Auto backup",
"Year"                  :"Year",
"Month"                 :"Month",
"Day"                   :"Day",
"Hour"                  :"Hour",
"Backup every"          :"Backup every",
"Cancel"                :"Cancel",
"Apply"                 :"Apply",
"Create Backup"         :"Create Backup",
"Export Excel"          :"Export Excel",
}
japanese_translation={
"Monthes"            :"Monthes",
"Packing materials"  :"Packing materials",
"Active Orders"      :"Action Orders",
"Final Products"     :"Final Products",
"HOME"               :"HOME",
'Products'           :'Products',
'Measuring Units'    :'Measuring Units',
'Raw Materials'      :'Raw Materials',
"Product Raw Materials":'Product Raw Materials',
'Orders'             :'Orders',
"Products"           :"Products",
"File"               :"File",
"Export"             :"Export",
"Import"             :"Import",
"View"               :"View",
"Themes"             :"Themes",
"Excell"             :"Excell",
"Word"               :"Word",
"INS Production Plan Document" :"INS Production Plan Guide book",
"About"              :"About",
"Backup"             :"Backup",
"Backup settings"    :"Backup settings",
"INS"                :"INS",
"White"              :"White",
"Dark Green"         :"Dark Green",
"Dark Blue"          :"Dark Blue",
"Language"           :"Language",
'Order Name'         :'Order Name',
'Quantity'           :'Quantity',
'From'               :'From',
'To'                 :'To',
'Add Order'          :'Add Order',
'Edit Order'         :'Edit Order',
"Material Name"      :"Material Name",
"Available Quantity" :"Available Quantity",
"Code"               :"Code",
'Add Material'       :'Add Material',
'Edit Material'      :'Edit Material' ,
"Material density"      :'Material density',
"Matiral Types"         :"Matiral Types",
"Product Name"          :"Product Name",
'Add Product'          :'Add Product',
'Edit Product'         :'Edit Product',
"Unit Name"             :"Unit Name",
"Value"                 :"Value",
'Add Unit'              :'Add Unit',
'Edit Unit'             :'Edit Unit',
"Manual backup"         :"Manual backup",
"Auto backup"           :"Auto backup",
"Year"                  :"Year",
"Month"                 :"Month",
"Day"                   :"Day",
"Hour"                  :"Hour",
"Backup every"          :"Backup every",
"Cancel"                :"Cancel",
"Apply"                 :"Apply",
"Create Backup"         :"Create Backup",
"Export Excel"          :"Export Excel",
}


languages={
    'en'   :english_translation,
    'arabic'    :arabic_translation,
    'italy'     :italy_translation,
    'french'    :french_translation,
    'japanese'  :japanese_translation,
}
